#!/usr/bin/php -q
<?php
/***************************************************************************
* copyright            : (C) 2001-2011 Advanced Internet Designs Inc.
* email                : forum@prohost.org
* $Id$
*
* This program is free software; you can redistribute it and/or modify it 
* under the terms of the GNU General Public License as published by the 
* Free Software Foundation; version 2 of the License, or 
* (at your option) any later version.
***************************************************************************/

require( "archive_utils");

$dir = FALSE;
$filename = FALSE;
$compress = FALSE;

if( !defined('argc') ){
	$argc = $_SERVER['argc'];
}

if( $argc == 1 ) {
	seterr("No arguments.\n\tSyntax: create_file_archive directory_name [archive_name] [use compression]\n\tIf no archive_name is specified the archive is echoed");
} 
if ( $argc >= 2 ) {
	$dir = preg_replace('!/+$!', '', $_SERVER['argv'][1]);
	if( !@is_dir($dir) ) {
		seterr("ERROR: [$dir] is not a valid valid directory.\nPlease specify a valid directory to package.");
	}
} 
if( $argc >= 3 ) {
	$filename = $_SERVER['argv'][2];
}
if( $argc >= 4 ) {
	$compress = $_SERVER['argv'][3];
	if( !( strcasecmp($compress, "1") || 
		   strcasecmp($compress,"true")  || 
		   strcasecmp($compress,"yes") ) ) {
		$compress = TRUE;
	}

	if( $compress && !extension_loaded('zlib') )	{
		seterr('The zlib extension that is required to compress the archive is not installed. Please install it or restart without compression.');
	}
}

create_file_archive( $dir, $filename, $compress );

