INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_redface.gif','Embarrassed',':blush:',1);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_razz.gif','Razz',':P~:-P~:razz:',2);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_mad.gif','Mad',':x~:-x~:mad:',3);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_lol.gif','Laughing',':lol:',4);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_cool.gif','Cool','8)~8-)~:cool:',5);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_confused.gif','Confused',':?~:-?~:???:',6);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_eek.gif','Shocked','8O~8-O~:shock:',7);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_surprised.gif','Surprised',':o~:-o~:eek:',8);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_sad.gif','Sad',':(~:-(~:sad:',9);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_smile.gif','Smile',':)~:-)~:smile:',10);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_biggrin.gif','Very Happy',':D~:-D~:grin:',11);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_cry.gif','Crying or Very Sad',':cry:~:((~:-((',12);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_evil.gif','Evil or Very Mad',':evil:',13);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_twisted.gif','Twisted Evil',':twisted:',14);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_rolleyes.gif','Rolling Eyes',':roll:',15);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_wink.gif','Wink',';)~;-)~:wink:',16);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_exclaim.gif','Exclamation',':!:',17);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_question.gif','Question',':?:',18);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_idea.gif','Idea',':idea:',19);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_arrow.gif','Arrow',':arrow:',20);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_neutral.gif','Neutral',':|~:-|~:neutral:',21);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_mrgreen.gif','Grin',':]~:-]~:brgin:',22);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_dead.gif','Dead','x(~:dead:',23);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_frown.gif','Frown',':frown:',24);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_nod.gif','Nod',':nod:',25);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_proud.gif','Proud',':proud:',26);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_smug.gif','Smug',':smug:',27);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_thumbsup.gif','Thumbs Up',':thumbup:',28);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_thumbdown.gif','Thumbs Down',':thumbdown:',29);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_uhoh.gif','Uh Oh',':uhoh:',30);
INSERT INTO {SQL_TABLE_PREFIX}smiley (img, descr, code, vieworder) VALUES ('icon_yawn.gif','Bored',':yawn:',31);
