INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (1,'icon_redface.gif','Embarassed',':blush:',1);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (2,'icon_razz.gif','Razz',':P~:-P~:razz:',2);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (3,'icon_mad.gif','Mad',':x~:-x~:mad:',3);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (4,'icon_lol.gif','Laughing',':lol:',4);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (5,'icon_cool.gif','Cool','8)~8-)~:cool:',5);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (6,'icon_confused.gif','Confused',':?~:-?~:???:',6);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (7,'icon_eek.gif','Shocked','8O~8-O~:shock:',7);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (8,'icon_surprised.gif','Surprised',':o~:-o~:eek:',8);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (9,'icon_sad.gif','Sad',':(~:-(~:sad:',9);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (10,'icon_smile.gif','Smile',':)~:-)~:smile:',10);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (11,'icon_biggrin.gif','Very Happy',':D~:-D~:grin:',11);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (12,'icon_cry.gif','Crying or Very Sad',':cry:~:((~:-((',12);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (13,'icon_evil.gif','Evil or Very Mad',':evil:',13);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (14,'icon_twisted.gif','Twisted Evil',':twisted:',14);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (15,'icon_rolleyes.gif','Rolling Eyes',':roll:',15);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (16,'icon_wink.gif','Wink',';)~;-)~:wink:',16);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (17,'icon_exclaim.gif','Exclamation',':!:',17);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (18,'icon_question.gif','Question',':?:',18);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (19,'icon_idea.gif','Idea',':idea:',19);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (20,'icon_arrow.gif','Arrow',':arrow:',20);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (21,'icon_neutral.gif','Neutral',':|~:-|~:neutral:',21);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (22,'icon_mrgreen.gif','Grin',':]~:-]~:brgin:',22);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (23,'icon_dead.gif','Dead','x(~:dead:',23);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (24,'icon_frown.gif','Frown',':frown:',24);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (25,'icon_nod.gif','Nod',':nod:',25);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (26,'icon_proud.gif','Proud',':proud:',26);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (27,'icon_smug.gif','Smug',':smug:',27);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (28,'icon_thumbsup.gif','Thumbs Up',':thumbup:',28);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (29,'icon_thumbdown.gif','Thumbs Down',':thumbdown:',29);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (30,'icon_uhoh.gif','Uh Oh',':uhoh:',30);
INSERT INTO {SQL_TABLE_PREFIX}smiley VALUES (31,'icon_yawn.gif','Bored',':yawn:',31);
