INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(1,'aiff','audio/x-aiff','AIFF File','sound.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(2,'wav','audio/x-wav','Wave File','sound.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(3,'midi','audio/midi','MIDI File','midi.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(4,'au','audio/basic','Sun ulaw-Compressed Audio File','sound.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(5,'mp3','audio/mpeg','MP3 File','sound.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(6,'rm','audio/x-realaudio','Real Audio','real.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(7,'gif','image/gif','GIF Image','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(8,'ico','image/ico','Icon File','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(9,'jpeg','image/jpeg','JPEG Image','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(10,'jpg','image/jpeg','JPEG Image','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(11,'tiff','image/tiff','TIFF Image','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(12,'tif','image/tiff','TIFF Image','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(13,'pict','image/x-pict','Macintosh PICT format','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(14,'bmp','image/x-win-bmp','BMP Image','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(15,'png','image/png','PNG Image','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(16,'mpeg','video/mpeg','MPEG Movie','video.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(17,'mpg','video/mpeg','MPEG Movie','video.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(18,'qt','video/quicktime','QuickTime Movie','video.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(19,'mov','video/quicktime','QuickTime Movie','video.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(20,'vivo','video/vnd.vivo','VIVO Movie','video.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(21,'avi','video/x-msvideo','Microsoft Video','video.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(22,'gz','application/x-gzip','GZIP Archive','tgz.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(23,'tar','application/x-tar','TAR Archive','tar.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(24,'zip','application/zip','ZIP Archive','tgz.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(25,'doc','application/msword','MS Word Document','word.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(26,'dot','application/msword','MS Word Document','word.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(27,'xls','application/vnd.ms-excel','MS Excel','excel.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(28,'ppt','application/vnd.ms-powerpoint','MS PowerPoint','ppt.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(29,'pdf','application/pdf','PDF Document','pdf.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(30,'rtf','application/rtf','Rich Text Format','txt.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(31,'htm','text/html','HTML Page','html.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(32,'html','text/html','HTML Page','html.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(33,'txt','text/plain','Plain Text','txt.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(34,'ps','application/postscript','Postscript','postscript.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(35,'swf','application/x-shockwave-flash','ShockWave Flash','flash.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(36,'exe','application/application','Binary File','binary.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(37,'bin','application/application','Binary File','binary.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(38,'sh','application/sh','UNIX Shell Script','sh.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(39,'hqx','application/mac-binhex40','Mac Binary','binary.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(40,'','application/octet-stream','Unknown','unknown.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(41,'pl','application/x-perl','Perl Script','source.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(42,'pm','application/x-perl','Perl Module','source.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime VALUES(43,'php','application/x-httpd-php','PHP Script','source.gif');
