INSERT INTO {SQL_TABLE_PREFIX}spiders (botname, useragent) VALUES ('Google', 'Googlebot');
INSERT INTO {SQL_TABLE_PREFIX}spiders (botname, useragent) VALUES ('Lycos', 'lycos');
INSERT INTO {SQL_TABLE_PREFIX}spiders (botname, useragent) VALUES ('Ask.com', 'Teoma');
INSERT INTO {SQL_TABLE_PREFIX}spiders (botname, useragent) VALUES ('What You Seek', 'whatuseek');
INSERT INTO {SQL_TABLE_PREFIX}spiders (botname, useragent) VALUES ('Internet Archive', 'archive_crawler');
INSERT INTO {SQL_TABLE_PREFIX}spiders (botname, useragent) VALUES ('Alexa Internet', 'ia_archiver');
INSERT INTO {SQL_TABLE_PREFIX}spiders (botname, useragent) VALUES ('Bing', 'msnbot');
INSERT INTO {SQL_TABLE_PREFIX}spiders (botname, useragent) VALUES ('Yahoo!', 'Slurp');
INSERT INTO {SQL_TABLE_PREFIX}spiders (botname, useragent) VALUES ('Cuil', 'twiceler');
INSERT INTO {SQL_TABLE_PREFIX}spiders (botname, useragent) VALUES ('Baidu', 'Baiduspider');
