INSERT INTO {SQL_TABLE_PREFIX}calendar (day, month, year, descr) VALUES ('1', '1', '*', 'New Year''s Day');
INSERT INTO {SQL_TABLE_PREFIX}calendar (day, month, year, descr) VALUES ('14', '2', '*', 'Valentine''s Day');
INSERT INTO {SQL_TABLE_PREFIX}calendar (day, month, year, descr) VALUES ('17', '3', '*', 'St. Patrick''s');
INSERT INTO {SQL_TABLE_PREFIX}calendar (day, month, year, descr) VALUES ('1', '4', '*', 'All Fool''s Day');
INSERT INTO {SQL_TABLE_PREFIX}calendar (day, month, year, descr) VALUES ('22', '4', '*', 'Earth Day');
INSERT INTO {SQL_TABLE_PREFIX}calendar (day, month, year, descr) VALUES ('5', '5', '*', 'Cinco de Mayo');
INSERT INTO {SQL_TABLE_PREFIX}calendar (day, month, year, descr) VALUES ('6', '6', '*', 'D-Day');
INSERT INTO {SQL_TABLE_PREFIX}calendar (day, month, year, descr) VALUES ('24', '10', '*', 'United Nations Day');
INSERT INTO {SQL_TABLE_PREFIX}calendar (day, month, year, descr) VALUES ('31', '10', '*', 'Halloween');
INSERT INTO {SQL_TABLE_PREFIX}calendar (day, month, year, descr) VALUES ('11', '11', '*', 'Veterans Day');
INSERT INTO {SQL_TABLE_PREFIX}calendar (day, month, year, descr) VALUES ('25', '12', '*', 'Christmas Day');
INSERT INTO {SQL_TABLE_PREFIX}calendar (day, month, year, descr) VALUES ('2', '*', '*', 'Second day of the month, do your time sheets.');
