INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('aiff','audio/x-aiff','AIFF File','sound.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('wav','audio/x-wav','Wave File','sound.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('midi','audio/midi','MIDI File','midi.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('au','audio/basic','Sun ulaw-Compressed Audio File','sound.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('mp3','audio/mpeg','MP3 File','sound.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('rm','audio/x-realaudio','Real Audio','real.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('gif','image/gif','GIF Image','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('ico','image/ico','Icon File','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('jpeg','image/jpeg','JPEG Image','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('jpg','image/jpeg','JPEG Image','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('tiff','image/tiff','TIFF Image','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('tif','image/tiff','TIFF Image','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('pict','image/x-pict','Macintosh PICT format','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('bmp','image/x-win-bmp','BMP Image','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('png','image/png','PNG Image','image.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('mpeg','video/mpeg','MPEG Movie','video.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('mpg','video/mpeg','MPEG Movie','video.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('qt','video/quicktime','QuickTime Movie','video.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('mov','video/quicktime','QuickTime Movie','video.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('vivo','video/vnd.vivo','VIVO Movie','video.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('avi','video/x-msvideo','Microsoft Video','video.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('gz','application/x-gzip','GZIP Archive','tgz.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('tar','application/x-tar','TAR Archive','tar.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('zip','application/zip','ZIP Archive','tgz.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('doc','application/msword','MS Word Document','word.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('dot','application/msword','MS Word Document','word.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('xls','application/vnd.ms-excel','MS Excel','excel.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('ppt','application/vnd.ms-powerpoint','MS PowerPoint','ppt.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('pdf','application/pdf','PDF Document','pdf.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('rtf','application/rtf','Rich Text Format','txt.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('htm','text/html','HTML Page','html.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('html','text/html','HTML Page','html.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('txt','text/plain','Plain Text','txt.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('ps','application/postscript','Postscript','postscript.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('swf','application/x-shockwave-flash','ShockWave Flash','flash.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('exe','application/application','Binary File','binary.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('bin','application/application','Binary File','binary.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('sh','application/sh','UNIX Shell Script','sh.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('hqx','application/mac-binhex40','Mac Binary','binary.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('*','application/octet-stream','Unknown','unknown.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('pl','application/x-perl','Perl Script','source.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('pm','application/x-perl','Perl Module','source.gif');
INSERT INTO {SQL_TABLE_PREFIX}mime (fl_ext,mime_hdr,descr,icon) VALUES('php','application/x-httpd-php','PHP Script','source.gif');
