<?php $cidxc = array (
  1 => 
  array (
    0 => 0,
    1 => 'Public Forums',
    2 => 'A test category for demonstration purposes.',
    3 => 3,
    4 => 0,
    5 => 
    array (
      1 => 1,
    ),
  ),
  2 => 
  array (
    0 => 0,
    1 => 'Private Forums',
    2 => 'Anoter test category for demonstration purposes.',
    3 => 3,
    4 => 0,
    5 => 
    array (
      2 => 2,
    ),
  ),
); ?>