#!/usr/local/bin/php -q
<?php

function make_lang_arr($path)
{
	$eng = file($path);
	foreach ($eng as $v) {
		$key = strtok($v, ':');
		$lang[$key] = $v;
	}

	return $lang;
}
	$lang = make_lang_arr('english/msg');
	$keys = array_keys($lang);
	
	echo count($lang)." messages in the english file\n";

	$dp = opendir('.');
	readdir($dp); readdir($dp); 
	while ($de = readdir($dp)) {
		if (!is_dir($de) || $de == 'english' || !@file_exists($de . '/msg')) {
			continue;
		}

		echo "checking: $de\n";
		$curl = make_lang_arr($de . '/msg');
		$i = 0;

		foreach ($keys as $v) {
			if (!isset($curl[$v])) {
				$curl[$v] = $lang[$v];
				$i++;
			}
		}
		if ($i) {
			echo "$i lines are new to $de/msg\n";
			if (!($fp = fopen($de . '/msg', 'w'))) {
				exit("can't open $de/msg for writing\n");
			}
			fwrite($fp, implode('', $curl));
			fclose($fp);
		}
	}
	closedir($dp);
?>
