name: Build FUDforum archive

on:
  push:
    branches: [ master ]
#pull_request:
#  branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code under $GITHUB_WORKSPACE
      uses: actions/checkout@v2

    - name: Generate archive file
      run: php create_fudforum_archive install 1 > fudforum_archive
          
    - name: Upload files required for install as artifact
      uses: actions/upload-artifact@v2
      with:
          name: fudforum-latest
          path: |
            fudforum_archive
            install.php
            upgrade.php
            uninstall.php
            README
            COPYING
            CREDITS
          if-no-files-found: error

    - name: Commit fudforum_archive back to repo
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add fudforum_archive
        git commit -m "Generated forum_archive"
        git push
